feat: used pyproject.toml instead of setup.py
ClearlyEnergy/helix-label pull request #18
Opened 2024-10-21 18:34 UTC by loydbanks

2024-10-21 18:36 UTC, paddatrapper requested changes

2024-10-21 18:36 UTC, paddatrapper commented on pyproject.toml
> +name = "label"
helix-label - it's too generic otherwise

2024-10-21 18:36 UTC, paddatrapper commented on pyproject.toml
> +    "Programming Language :: Python :: 2",
Does this support python 2?

2024-10-25 07:24 UTC, loydbanks commented on pyproject.toml
> +    "Programming Language :: Python :: 2",
I don't know how to test for that but it's shown in the classifiers on setup.py

2024-10-25 08:25 UTC, paddatrapper approved these changes

2024-10-28 08:39 UTC, merged